A = A
B = B
C = REMOVED-Reason:The sounds of "k" and "s" can fully replace the sound of "c" in most cases. For example, "cat" can be spelled "kat".
D = D
E = E
F = F
G = G
H = h
I = I
J = REMOVED-Reason:The "j" sound can be replaced with "g" as in "jam" becoming "gam" or "zh" as in "pleasure" becoming "pleazhur".
K = K
L = L
M = M
N = N
O = O
P = P
Q = REMOVED-Reason:The "kw" sound can be replaced with either "kw" or "k," as in "quick" becoming "kwik" or "kwick.".
R = R
S = S
T = T
U = U
V = REMOVED-Reason:The "v" sound can be replaced with "f" as in "victory" becoming "fictory" or "uh" as in "move" becoming "muhv".
W = REMOVED-Reason:The "w" sound can be replaced with "u" as in "wind" becoming "uind".
X = REMOVED-Reason:The "ks" sound can be used instead, such as spelling "box" as "boks."
Y = REMOVED-Reason:The function of "y" can be replaced by "i" as in "myth" becoming "mith" or "e" as in "baby" becoming "beby".
Z = Z
